services: 
  app: 
    build: ./app
    ports: 
      - "3000:3000"
    depends_on: 
      redis: 
        condition: service_healthy
    
  redis: 
    image: "redis:7-alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
